### ISSUE TITLE
duplicate entry: META-INF/atomicfu.kotlin_module

### ISSUE THREAD

**Issue by SUPERCILEX** [Kotlin/kotlinx.coroutines#1064]
I've tried [this](https://github.com/Kotlin/kotlinx.coroutines/issues/1059#issuecomment-476805836) and it doesn't work. I'm a bit stuck. 😢

**Comment by eakteam** [comment]
@SUPERCILEX , i have tried with 

```
packagingOptions {
        pickfirst 'META-INF/atomicfu.kotlin_module'
}
```

```
packagingOptions {
        pickfirst 'META-INF/*'
}
```

```
packagingOptions {
        pickfirst '**'
}
```

and it is not working too !

**Comment by kherlopian2** [comment]
> packagingOptions {
>         pickFirst 'META-INF/kotlinx-io.kotlin_module'
>         pickFirst 'META-INF/atomicfu.kotlin_module'
>         pickFirst 'META-INF/kotlinx-coroutines-io.kotlin_module'
>     }


that worked with me.

**Comment by eakteam** [comment]
@kherlopian2 , for me still not working

**Comment by SUPERCILEX** [comment]
@kherlopian2 Nope, not working. 😢 @eakteam Are you using dynamic feature feature modules or instant apps?

**Comment by eakteam** [comment]
@kherlopian2 , Yes i am using Dynamic Feature Modules and this packaging options rules i have added in every build.gradle

**Comment by SUPERCILEX** [comment]
Neat, so that's gotta be the bug somehow! I want to hear @qwwdfsad's thoughts, but then I'll file an issue if it's really Google's fault.

**Comment by eakteam** [comment]
@SUPERCILEX , sure that this is a minor bug and for sure it will be solved, but @qwwdfsad i think its not his fault and maybe it is related really to Android Build Tollchain. I have opened a bug for this and they have reviewed it : 

https://issuetracker.google.com/issues/129323351

I am using latest Android Studio 3.5 Canary 9. @SUPERCILEX  what Android Studio version do you use ? I mean this is happening in every version since latest coroutine release or only to 3.5 canary 9 version ?

**Comment by SUPERCILEX** [comment]
Dope. And I've tried going back to alpha 6 I think. Still broken so it was definitely introduced by coroutines. Still seems like a tooling bug though. 🤷‍♂️

**Comment by eakteam** [comment]
@SUPERCILEX , i understand , thanks for saving time not leaving me to downgrade too :D :D ... It will be fixed don't worry, it is just a very minor issue. I downgrade to 1.1.1 of coroutines but needed to fix this just for curiosity to test how the new version works ....

And some bug are normal, it is just Alpha version. 
Best Regards, if they reply me to the bug report on Google i will reply back here to you to let you know, or just star that issue to stay updated

**Comment by eakteam** [comment]
@SUPERCILEX , thanks for providing Google with open source project, it is really important and they will solve this for sure in this way. I can't share mine because is Close Source, so thank you for supporting !
Best Regards

**Comment by eakteam** [comment]
@SUPERCILEX , something else. Can you please write me an email at info@eakteam.com and if you can please explain me for what purpose is you app because i like to discuise something cool.

**Comment by eakteam** [comment]
@SUPERCILEX , i have solved id by adding this in my app gradle file

```
configurations {
        compile.exclude group: 'org.jetbrains.kotlinx', module: 'atomicfu-common'
    }
```

**Comment by LouisCAD** [comment]
Same problem with version 1.2.0-alpha on my side.
Here's the error:
```
> Task :sample:mergeDebugJavaResource FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample:mergeDebugJavaResource'.
> 1 exception was raised by workers:
  com.android.builder.merge.DuplicateRelativeFileException: More than one file was found with OS independent path 'META-INF/atomicfu.kotlin_module'
```
And here's a permalink to a **reproducing project**: https://github.com/LouisCAD/Splitties/tree/e2389213a82aa91ca4ecf4a05fc67438e7c5ffd0
You can try it by just running `./gradlew :sample:assembleDebug`.

**Comment by SUPERCILEX** [comment]
@eakteam doesn't that break things at runtime though?

**Comment by eakteam** [comment]
@SUPERCILEX , No, for me everything is running OK. There are 2 modules in group `org.jetbrains.kotlinx`

Remember to exclude only `atomicfu-common` module

**Comment by qwwdfsad** [comment]
Thanks for the reproduce and possible workarounds!
`kotlin_module` file is generated and used by the compiler, so we have no control over it.

This issue will be solved in 1.3.40 on the compiler side: https://youtrack.jetbrains.com/issue/KT-30344
And in AS independently; https://issuetracker.google.com/issues/125696148

I will leave the issue open for a while to make it easier for users to find a workaround.

**Comment by JakeWharton** [comment]
If you're using Gradle you can specify `archivesBaseName` to generate modules with different names (and thus different `.kotlin_module` file names) to avoid collisions.

**Comment by eakteam** [comment]
I don't understand why this is not solved yet in `alpha-2` but we should use still the workaround ?

**Comment by JakeWharton** [comment]
The problem is not in this library

**Comment by eakteam** [comment]
Hmmmm, but this can contains in the aar the workaround to simplify things for new users, than after it is finally solved can edit back ... Anyway just my thoughts.

**Comment by Pranipus** [comment]
```
android {
    ...
    packagingOptions {
        pickFirst("META-INF/atomicfu.kotlin_module")
    }
    ...
}
```

Can confirm this worked for me^.

**Comment by eakteam** [comment]
This issue is still happening with latest `Kotlin 1.3.30` and latest `Coroutines 1.2.0`.
I don't know if should be fixed by next `Android Studio` version or by `Kotlin` or `Coroutines` library
We still need to implement the workarounds to skip the failure about `duplicate entry`

**Comment by qwwdfsad** [comment]
>This issue is still happening with latest Kotlin 1.3.30 and latest Coroutines 1.2.0.

It was told above that it is not the library issue and that on Kotlin side it will be fixed in 1.3.40 and in AS 3.5 Canary 12.

**Comment by eakteam** [comment]
@qwwdfsad , sorry i have missed that comment 😊. 
Thanks for confirming it !

**Comment by elizarov** [comment]
It looks that is a side-effect of leaked atomicfu dependency. `atomicfu.kotlin_module` will disappear in version `1.2.1`. See #1120

**Comment by rwsbillyang** [comment]
> packagingOptions {
>         pickFirst 'META-INF/kotlinx-io.kotlin_module'
>         pickFirst 'META-INF/atomicfu.kotlin_module'
>         pickFirst 'META-INF/kotlinx-coroutines-io.kotlin_module'
>     }



> ```
> packagingOptions {
>         pickFirst 'META-INF/kotlinx-io.kotlin_module'
>         pickFirst 'META-INF/atomicfu.kotlin_module'
>         pickFirst 'META-INF/kotlinx-coroutines-io.kotlin_module'
>     }
> ```
> that worked with me.

that worked with me (kotlin 1.3.30 + coroutines1.2.0) too, thanks.

**Comment by Sunbreak** [comment]
@elizarov @qwwdfsad After upgrading to kotlin-v1.3.31 & coroutine-1.2.1, the leak of "atomicfu.kotlin_module" is fixed, but the leak of "kotlinx-coroutines-core.kotlin_module" is still there

**Reproduce**
git clone https://github.com/Sunbreak/notepad-sdk-mpp
cd androidSample && ./gradlew assembleDebug

**Comment by elizarov** [comment]
Two copies of `kotlinx-coroutines-core.kotlin_module` should be present in any kotlin project: one from the comes from `kotlin-stdlib` the other comes from `kotlin-stdlib-common` (which is always brought in by a transitive dependency from `kotlin-stdlib`). It should not depend on whether you use `kotlinx-coroutines` or not.

**Comment by manishpatelgt** [comment]
By adding below line resolve issue

>  exclude 'META-INF/atomicfu.kotlin_module'

**Comment by namanh007** [comment]
> ```
> packagingOptions {
>         pickFirst 'META-INF/kotlinx-io.kotlin_module'
>         pickFirst 'META-INF/atomicfu.kotlin_module'
>         pickFirst 'META-INF/kotlinx-coroutines-io.kotlin_module'
>     }
> ```
> 
> that worked with me.

that worked for me

**Comment by dhirajhimani** [comment]
You could try 
`
    packagingOptions {
        exclude 'META-INF/atomicfu.kotlin_module'
    }`

**Comment by LouisCAD** [comment]
I still have to put `pickFirst("META-INF/kotlinx-coroutines-core.kotlin_module")` in the `packagingOptions` to be able to run Android instrumented tests.

**Comment by LouisCAD** [comment]
I still have to put `pickFirst("META-INF/kotlinx-coroutines-core.kotlin_module")` in the `packagingOptions` to be able to run Android instrumented tests from a multiplatform project as of Kotlin 1.3.50 and kotlinx.coroutines 1.3.1.

**Comment by mirokolodii** [comment]
Still an issue for me in multiplatform project during project build, caused by this line:
````
 commonMain.dependencies {
            implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:1.3.2"
````
Message is `More than one file was found with OS independent path 'META-INF/kotlinx-coroutines-core.kotlin_module'`

AS ver. 3.5.2
Kotlin ver 1.3.50
Coroutines ver. 1.3.2

Workaround with packagingOptions doesn't work, probably packagingOptions are related to Android part, while this is a common one.

**Comment by linean** [comment]
@mirokolodii Did you manage to solve it?

**Comment by mirokolodii** [comment]
@linean Yes, issue was indeed fixed by `packagingOptions`, but it was required to put it into my app module instead multiplatform one, even though there are no dependencies to coroutines in app module. 
Please note that I've also added `pickFirst 'META-INF/ktor-*'`, as I had similar issue with Ktor library.
````
android {
packagingOptions {
        pickFirst 'META-INF/kotlinx-io.kotlin_module'
        pickFirst 'META-INF/atomicfu.kotlin_module'
        pickFirst 'META-INF/kotlinx-coroutines-io.kotlin_module'
        pickFirst 'META-INF/kotlinx-coroutines-core.kotlin_module'
        pickFirst 'META-INF/kotlinx-serialization-runtime.kotlin_module'
        pickFirst 'META-INF/ktor-*'
    }
}
````

**Comment by wangyongf** [comment]
> @linean Yes, issue was indeed fixed by `packagingOptions`, but it was required to put it into my app module instead multiplatform one, even though there are no dependencies to coroutines in app module.
> Please note that I've also added `pickFirst 'META-INF/ktor-*'`, as I had similar issue with Ktor library.
> 
> ```
> android {
> packagingOptions {
>         pickFirst 'META-INF/kotlinx-io.kotlin_module'
>         pickFirst 'META-INF/atomicfu.kotlin_module'
>         pickFirst 'META-INF/kotlinx-coroutines-io.kotlin_module'
>         pickFirst 'META-INF/kotlinx-coroutines-core.kotlin_module'
>         pickFirst 'META-INF/kotlinx-serialization-runtime.kotlin_module'
>         pickFirst 'META-INF/ktor-*'
>     }
> }
> ```

hello @mirokolodii , I have the same problem in my kotlin multiplatform project, so, we can only solve the problem by adding endless pickFirst statement in packagingOptions block? Any better way?

**Comment by LouisCAD** [comment]
> Do you have the same error `com.android.builder.merge.DuplicateRelativeFileException: More than one file was found with OS independent path ... ` otherwise?

@qwwdfsad No, I don't.

**Comment by mirokolodii** [comment]
> > @linean Yes, issue was indeed fixed by `packagingOptions`, but it was required to put it into my app module instead multiplatform one, even though there are no dependencies to coroutines in app module.
> > Please note that I've also added `pickFirst 'META-INF/ktor-*'`, as I had similar issue with Ktor library.
> > ```
> > android {
> > packagingOptions {
> >         pickFirst 'META-INF/kotlinx-io.kotlin_module'
> >         pickFirst 'META-INF/atomicfu.kotlin_module'
> >         pickFirst 'META-INF/kotlinx-coroutines-io.kotlin_module'
> >         pickFirst 'META-INF/kotlinx-coroutines-core.kotlin_module'
> >         pickFirst 'META-INF/kotlinx-serialization-runtime.kotlin_module'
> >         pickFirst 'META-INF/ktor-*'
> >     }
> > }
> > ```
> 
> hello @mirokolodii , I have the same problem in my kotlin multiplatform project, so, we can only solve the problem by adding endless pickFirst statement in packagingOptions block? Any better way?

No idea to be honest. I expect they will fix it eventually, but for now I've just added those things and forgot about them.

**Comment by elizarov** [comment]
See the recent problem with `ktor` dependency: https://github.com/Kotlin/kotlinx.coroutines/issues/1797 It will get fixed in the next release (already in `develop`)

**Comment by AliAzaz** [comment]
I'm getting this error while generating signed debug apk:

    Entry name 'META-INF/lifecycle-livedata-ktx_release.kotlin_module' collided 


Anyone have any possible solution for it. @elizarov ?

**Comment by vivekwolf123** [comment]
I tried -

```
packagingOptions {
        pickFirst 'META-INF/kotlinx-io.kotlin_module'
        pickFirst 'META-INF/atomicfu.kotlin_module'
        pickFirst 'META-INF/kotlinx-coroutines-io.kotlin_module'
}
```

And

```
configurations {
        compile.exclude group: 'org.jetbrains.kotlinx', module: 'atomicfu-common'
}
```

Still doesn't work  :(

I use Android Studio version 4.1.1 and Kotlin Coroutines version 1.4.2-native-mt.

The error I get - 

`Modules contain entry 'root/META-INF/kotlinx-coroutines-core.kotlin_module' with different content.`

**Comment by LouisCAD** [comment]
@AliAzaz This is not related to kotlinx.coroutines, and the solution is already in the comments here (`pickFirst` or `exclude`).

This is a bug in AGP (the Android Gradle Plugin), that is fixed since its version 7.0.0-alpha01, so you can upgrade from version 4.x if you are ready to test the next AGP and Android Studio 2020.3.1 early.

**Comment by ChinGyi2019** [comment]
> @AliAzaz This is not related to kotlinx.coroutines, and the solution is already in the comments here (`pickFirst` or `exclude`).
> 
> This is a bug in AGP (the Android Gradle Plugin), that is fixed since its version 7.0.0-alpha01, so you can upgrade from version 4.x if you are ready to test the next AGP and Android Studio 2020.3.1 early.

how can i fix this fukking shit problem

**Comment by Siddharth-sing** [comment]
> I'm getting this error while generating signed debug apk:
> 
> ```
> Entry name 'META-INF/lifecycle-livedata-ktx_release.kotlin_module' collided 
> ```
> 
> Anyone have possible solution for it. @elizarov ?

android {
    ...
    packagingOptions {
        pickFirst("META-INF/atomicfu.kotlin_module")
    }
    ...
}
This worked for my project for the same error.
