### ISSUE TITLE
Strange behaviour when using kotlin.Result with operators

### ISSUE THREAD

**Issue by batadamnjanovic** [Kotlin/kotlinx.coroutines#2430]
Kotlin version: 1.3.72
Coroutines version: 1.3.9

When using zip or combine operator(only tested with those) to combine two repository methods which both have kotlin.Result as return type, we get kotlin.Result wrapped into another kotlin.Result.

This is an example of how the method looks like and their usage with zip operator and the log of the returned object
![Screen Shot 2020-12-04 at 6 15 06 PM](https://user-images.githubusercontent.com/22530295/101193403-d26a3900-365c-11eb-9c27-7a6e61446e54.png)
![Screen Shot 2020-12-04 at 6 16 03 PM](https://user-images.githubusercontent.com/22530295/101193406-d39b6600-365c-11eb-8f53-67a29824ed2a.png)
![Screen Shot 2020-12-04 at 6 21 02 PM](https://user-images.githubusercontent.com/22530295/101194301-17db3600-365e-11eb-83c2-de17d1627c09.png)

**Comment by qwwdfsad** [comment]
Thanks for the report.
This is likely to be the https://youtrack.jetbrains.com/issue/KT-41429 compiler bug that was fixed in 1.4.20.
Please update and see if that helps.

**Comment by batadamnjanovic** [comment]
It is still the same with 1.4.20. Let me know if I need to provide more information

**Comment by batadamnjanovic** [comment]
It is still the same with 1.4.20. Let me know if I need to provide more information.

**Comment by qwwdfsad** [comment]
Could you please provide a self-contained reproducer that I can copy-paste and run?

**Comment by batadamnjanovic** [comment]
Here is the project: https://github.com/batadamnjanovic/kotlinresultcompilerbug

And the test file: https://github.com/batadamnjanovic/kotlinresultcompilerbug/blob/master/app/src/test/java/com/kotlinflow/kotlinresultcompilerbug/ExampleUnitTest.kt

**Comment by qwwdfsad** [comment]
Thanks! This is clearly a compiler bug, filed https://youtrack.jetbrains.com/issue/KT-44527, please keep track of it there
