### ISSUE TITLE
1.6.0-native-mt broken with shareIn

### ISSUE THREAD

**Issue by PaulWoitaschek** [Kotlin/kotlinx.coroutines#3136]
The following example:

```kotlin
  @Test
  fun sharingTest() {
    runBlocking {
      flowOf(Unit).shareIn(GlobalScope, SharingStarted.WhileSubscribed())
        .collect { println(it) }
    }
  }
```

Throws an exception on native (tried on iosSimulatorArm64) using Kotlin 1.6.10 and coroutines 1.6.0. This was working fine with kotlin 1.5.2.

```
kotlin.IllegalStateException: Cannot start an undispatched coroutine in another thread DefaultDispatcher from current MainThread
kotlin.IllegalStateException: Cannot start an undispatched coroutine in another thread DefaultDispatcher from current MainThread
	at kotlin.Throwable#<init>(/opt/buildAgent/work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Throwable.kt:24)
	at kotlin.Exception#<init>(/opt/buildAgent/work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:23)
	at kotlin.RuntimeException#<init>(/opt/buildAgent/work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:34)
	at kotlin.IllegalStateException#<init>(/opt/buildAgent/work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:70)
	at kotlinx.coroutines.startCoroutine#internal(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/native/src/Builders.kt:136)
	at kotlinx.coroutines#startAbstractCoroutine(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/native/src/Builders.kt:118)
	at kotlinx.coroutines.AbstractCoroutine#start(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/AbstractCoroutine.kt:130)
	at kotlinx.coroutines#launch__at__kotlinx.coroutines.CoroutineScope(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/Builders.common.kt:56)
	at kotlinx.coroutines.flow.launchSharing#internal(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/flow/operators/Share.kt:209)
	at kotlinx.coroutines.flow#shareIn__at__kotlinx.coroutines.flow.Flow<0:0>(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/flow/operators/Share.kt:147)
	at kotlinx.coroutines.flow#shareIn$default__at__kotlinx.coroutines.flow.Flow<0:0>(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/flow/operators/Share.kt:135)
	at com.yazio.shared.common.property.FrozenPropertyTest.$sharingTest$lambda-1COROUTINE$0.invokeSuspend#internal(/Users/ph1b/repos/yazio/shared/common/src/commonTest/kotlin/com.yazio.shared.common.property/FrozenPropertyTest.kt:29)
	at kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(/opt/buildAgent/work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/coroutines/ContinuationImpl.kt:30)
	at kotlinx.coroutines.DispatchedTask#run(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/native/src/Debug.kt:17)
	at kotlinx.coroutines.EventLoopImplBase#processNextEvent(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/EventLoop.common.kt:281)
	at kotlinx.coroutines#runEventLoop(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/native/src/Builders.kt:87)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking#internal(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/native/src/Builders.kt:74)
	at kotlinx.coroutines#runBlocking(/opt/buildAgent/work/6326934d18cfe24e/kotlin/libraries/stdlib/src/kotlin/contracts/ContractBuilder.kt:56)
	at kotlinx.coroutines#runBlocking$default(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/native/src/Builders.kt:35)
	at com.yazio.shared.common.property.FrozenPropertyTest#sharingTest(/Users/ph1b/repos/yazio/shared/common/src/commonTest/kotlin/com.yazio.shared.common.property/FrozenPropertyTest.kt:28)
	at com.yazio.shared.common.property.$FrozenPropertyTest$test$0.$sharingTest$FUNCTION_REFERENCE$4.invoke#internal(/Users/ph1b/repos/yazio/shared/common/src/commonTest/kotlin/com.yazio.shared.common.property/FrozenPropertyTest.kt:27)
	at com.yazio.shared.common.property.$FrozenPropertyTest$test$0.$sharingTest$FUNCTION_REFERENCE$4.$<bridge-UNNN>invoke(/Users/ph1b/repos/yazio/shared/common/src/commonTest/kotlin/com.yazio.shared.common.property/FrozenPropertyTest.kt:27)
	at kotlin.native.internal.test.BaseClassSuite.TestCase#run(/opt/buildAgent/work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/TestSuite.kt:85)
	at kotlin.native.internal.test.TestRunner.run#internal(/opt/buildAgent/work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/TestRunner.kt:245)
	at kotlin.native.internal.test.TestRunner.runIteration#internal(/opt/buildAgent/work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/TestRunner.kt:271)
	at kotlin.native.internal.test.TestRunner#run(/opt/buildAgent/work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/TestRunner.kt:286)
	at kotlin.native.internal.test#testLauncherEntryPoint(/opt/buildAgent/work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/Launcher.kt:30)
	at kotlin.native.internal.test#main(/opt/buildAgent/work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/Launcher.kt:34)
	at <global>.Konan_start(/opt/buildAgent/work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/Launcher.kt:33)

```

**Comment by petarmarijanovicfive** [comment]
Same here

**Comment by PaulWoitaschek** [comment]
Can we get a hotfix for this? This forces us to stay on 1.5

**Comment by qwwdfsad** [comment]
We're aiming to release 1.6.1 along with 1.6.1-native-mt next wekk

**Comment by PaulWoitaschek** [comment]
@qwwdfsad 
Next week has passed, do you have any news on this?

**Comment by qwwdfsad** [comment]
Sorry for the delay, we had to postpone the release for now. Please stay tuned for the updates

**Comment by petarmarijanovicfive** [comment]
@qwwdfsad maybe an ETA for this? It pops up from time to time and we have to create some partial hotfixes because we are waiting for the fix in the new version

**Comment by qwwdfsad** [comment]
1.6.1-native-mt is out

**Comment by remy-bardou-lifeonair** [comment]
Was this really fixed by `1.6.1-native-mt`? I'm encountering the exact same crash!

Using 1.6.1.0-native-mt and new memory model. The crash seems to originate from using `WhileSubscribed()`. Switching to `Eagerly` for example fixes it.

**Comment by chippmann** [comment]
@qwwdfsad This issue still exists if one enables the new memory manager:
```
    targets
        .filterIsInstance<org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget>()
        .forEach { kotlinNativeTarget ->
            with(kotlinNativeTarget) {
                binaries.all {
                        // enabling experimental memory model because ktor 2.x does not work otherwise on native atm: https://youtrack.jetbrains.com/issue/KTOR-4260/Ktor-client-Curl-engine-crash
                        binaryOptions["memoryModel"] = "experimental"
                        // because we need the new memory model for native targets because of the issue outlined above, we also want to enable the experimental concurrent mark and sweep gc to reduce gc pauses as much as possible
                        // see: https://kotlinlang.org/docs/whatsnew1620.html#concurrent-implementation-for-the-sweep-phase-in-new-memory-manager
                        freeCompilerArgs += "-Xgc=cms"

                        // better native stacktraces with libbacktrace: https://kotlinlang.org/docs/whatsnew1620.html#better-stack-traces-with-libbacktrace
                        // disadvantage: slightly slower link times; but the better output definitely makes up for it!
                        binaryOptions["sourceInfoType"] = "libbacktrace"
                }
            }
        }
```

**Comment by LouisCAD** [comment]
Yup, and the new memory manager is becoming the default in 1.7.20 (there's an ongoing RC)

**Comment by petarmarijanovicfive** [comment]
@chippmann And yes, you don't need to use the `native-mt` version anymore 😁

**Comment by sigma-stochanskyi** [comment]
Working with 1.6.3-native-mt version on KMM. Facing same issue on iOS. Does someone else have this issue or is there any fix for that?

**Comment by LouisCAD** [comment]
Stop using the native-mt, not needed anymore with Kotlin 1.7.20+

**Comment by remcomokveld** [comment]
Would probably be good to update the documentation here then. Also it is now referring to a 1.6.4-native-mt which doesn't exist

**Comment by LouisCAD** [comment]
I bet you could get a doc updating PR accepted 🙂
