### ISSUE TITLE
Coroutines Dispatchers consume too much CPU

### ISSUE THREAD

**Issue by vvenka57** [Kotlin/kotlinx.coroutines#3192]
Hello,

We are currently looking into an issue with one of our apps where we are noticing very high CPU usage when we started switching coroutine context. Here is a pseudo code.

```
rxCompletable(Dispatchers.Default) {
   performValidations()
   performDataSetup()
   
   withContext(Dispatchers.IO) {
     performAPICall1()
   }

   performDataSetup()
   
   withContext(Dispatchers.IO) {
     performAPICall2()
   }

   performDataSetup()
}
```

Previously, we used Dispatchers.IO as global context and did not switch context and things were fine. Example below.

```
rxCompletable(Dispatchers.IO) {
   performValidations()
   performDataSetup()

   performAPICall1()

   performDataSetup()
   
   performAPICall2()

   performDataSetup()
}
```

I see the following in threaddump.

```
"DefaultDispatcher-worker-2" #79 daemon prio=5 os_prio=0 cpu=102793.08ms elapsed=2842.51s allocated=56877M defined_classes=1 tid=0x00007f46f401f800 nid=0x89 waiting on condition  [0x00007f478014e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.12/Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.12/LockSupport.java:357)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park(CoroutineScheduler.kt:783)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark(CoroutineScheduler.kt:728)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:711)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

"DefaultDispatcher-worker-6" #85 daemon prio=5 os_prio=0 cpu=81377.70ms elapsed=2636.71s allocated=44908M defined_classes=0 tid=0x00007f46f401e000 nid=0x96 waiting on condition  [0x00007f473b6fd000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.12/Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.12/LockSupport.java:357)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park(CoroutineScheduler.kt:783)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark(CoroutineScheduler.kt:728)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:711)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

"DefaultDispatcher-worker-4" #90 daemon prio=5 os_prio=0 cpu=65744.46ms elapsed=2508.38s allocated=36490M defined_classes=0 tid=0x00007f473424f000 nid=0x9c waiting on condition  [0x00007f46e99ea000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.12/Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.12/LockSupport.java:357)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park(CoroutineScheduler.kt:783)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark(CoroutineScheduler.kt:728)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:711)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

.............. and more
```

<img width="779" alt="image" src="https://user-images.githubusercontent.com/33668756/154380064-b031c2aa-7fc7-45db-8173-a5dc30c0c43f.png">

Setting `kotlinx.coroutines.scheduler=off` did not fix the issue.

We use `coroutines version 1.3.5`

Can someone please help with this?

**Comment by qwwdfsad** [comment]
I would suggest to update to `kotlinx.coroutines` 1.4.3+ where all the previous issues with dispatchers were fixed and, if it won't help, attempt to extract a small reproducer for us to investigate

**Comment by vvenka57** [comment]
Thanks for your quick response. I will try to update to the recommended version and give it a try. 

Can you also look at both the patterns and let me know which one is recommended?

**Comment by vvenka57** [comment]
@qwwdfsad I upgraded kotlinx.coroutines version to 1.6.0 and can confirm that the issue still exists.

**Comment by qwwdfsad** [comment]
Is it possible for you to extract a self-contained reproducer?

>Setting kotlinx.coroutines.scheduler=off did not fix the issue.

Prior to 1.6.0 (where this option has been removed), this is a good indicator something else is off. It's easy to check by e.g. replacing `Dispatchers.Default` with `ForkJoinPool.commonPool().asCoroutineDispatcher()` and `Dispathcers.IO` with `ForkJoinPool(64).asCoroutineDispatcher()` and see if the problem still persists. (NB: it **has to be** different dispatchers)

If the problem is gone when replacing coroutines dispatchers, then it's an issue on our side. Self-contained reproducer or a profile (e.g. by `async-profiler`) will be very helpful then
