### ISSUE TITLE
1.6.2: JS(IR) - Atomicfu Runtime not found

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/kotlinx.coroutines#3305]
After updating to `1.6.2`, it is not possible to build the project, if it contains a JS(IR) sourceset.

reproducer:
```kt
plugins {
    kotlin("multiplatform") version "1.6.21"
}

repositories {
    mavenCentral()
}

kotlin {
    jvm()
    js(IR) {
        browser()
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.2")
            }
        }
    }
}
```

Project: https://github.com/hfhbd/repro-coroutines162-JS-IR

```stacktrace
e: Could not find "org.jetbrains.kotlin:kotlinx-atomicfu-runtime" in [/Users/philipwedemann/Library/Application Support/kotlin/daemon]
e: java.lang.IllegalStateException: FATAL ERROR: Could not find "org.jetbrains.kotlin:kotlinx-atomicfu-runtime" in [/Users/philipwedemann/Library/Application Support/kotlin/daemon]
	at org.jetbrains.kotlin.ir.backend.js.KlibKt$toResolverLogger$1.fatal(klib.kt:117)
	at org.jetbrains.kotlin.library.KotlinLibrarySearchPathResolver.resolve(SearchPathResolver.kt:175)
	at org.jetbrains.kotlin.library.SearchPathResolver$DefaultImpls.resolve$default(SearchPathResolver.kt:20)
	at org.jetbrains.kotlin.library.SearchPathResolverKt.resolve(SearchPathResolver.kt:29)
	at org.jetbrains.kotlin.library.resolver.impl.KotlinLibraryResolverImpl$resolveDependencies$2$2.invoke(KotlinLibraryResolverImpl.kt:122)
	at org.jetbrains.kotlin.library.resolver.impl.KotlinLibraryResolverImpl$resolveDependencies$2$2.invoke(KotlinLibraryResolverImpl.kt:122)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at org.jetbrains.kotlin.library.resolver.impl.KotlinLibraryResolverImpl.resolveDependencies(KotlinLibraryResolverImpl.kt:135)
	at org.jetbrains.kotlin.library.resolver.impl.KotlinLibraryResolverImpl.resolveWithDependencies(KotlinLibraryResolverImpl.kt:44)
	at org.jetbrains.kotlin.ir.backend.js.JsLibraryResolverKt.jsResolveLibraries(JsLibraryResolver.kt:51)
	at org.jetbrains.kotlin.ir.backend.js.ModulesStructure.<init>(klib.kt:643)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.prepareAnalyzedSourceModule(klib.kt:540)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.prepareAnalyzedSourceModule$default(klib.kt:527)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:244)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:178)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:71)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:91)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:200)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:77)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:367)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:309)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl$rebuild(IncrementalCompilerRunner.kt:115)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:167)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:77)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:68)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:565)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1807)
```

**Comment by mpetuska** [comment]
I had the same issue. Fortunately, downgrading to 1.6.1 "fixed" it for now.

**Comment by mvicsokolova** [comment]
The WA for this is adding compiler plugin dependency, like this:
```kotlin
sourceSets {
        commonMain {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.2")
                implementation("org.jetbrains.kotlin:atomicfu:1.6.21") // atomicfu compiler plugin dependency
            }
        }
    }
```

**Comment by mvicsokolova** [comment]
`kotlinx.atomicfu` with the corresponding fix was released `0.17.3 `.
New version of `kotlinx.coroutines` with updated `kotlinx.atomicfu` will be released soon.

**Comment by joffrey-bion** [comment]
Hey, any updates on this?

**Comment by dkhalanskyjb** [comment]
Fixed in #3321.

**Comment by fluidsonic** [comment]
I have this issue after updating from 1.6.0 to 1.6.4.
Even though atomicfu resolves to 1.17.3 I still get this error.

Build Scan: https://scans.gradle.com/s/za65vgcq2paza

```sh
git clone git@github.com:fluidsonic/fluid-graphql.git -b coroutines-1.6.4
cd fluid-graphql
./gradlew build
```

```text
> Task :fluid-graphql-execution:compileKotlinJs FAILED
e: Could not find "org.jetbrains.kotlin:kotlinx-atomicfu-runtime" in [/Users/marc/Library/Application Support/kotlin/daemon]
e: java.lang.IllegalStateException: FATAL ERROR: Could not find "org.jetbrains.kotlin:kotlinx-atomicfu-runtime" in [/Users/marc/Library/Application Support/kotlin/daemon]
```

**Comment by amal** [comment]
@mgroth0 nope just returned to stable coroutines for now.

**Comment by mvicsokolova** [comment]
Hi!
This issue was fixed in `AtomicfuGradlePlugin`: https://github.com/Kotlin/kotlinx-atomicfu/pull/283

As a temporary WA you can add this dependency to the jsMain sourceSet:
```
implementation("org.jetbrains.kotlin:kotlinx-atomicfu-runtime:1.8.20-RC")
```

**Comment by hoangchungk53qx1** [comment]
try this 
https://github.com/Kotlin/kotlinx.coroutines/issues/3305
